module ErrorCodes
  INVALID_PRICE_RULE_TYPE = 1
  INVALID_PRICE_RULE_CONFIG = 2
  INVALID_MODEL_VALUE = 3
  ALREADY_EXISTING_PRODUCT = 4
  UNSUPPORTED_PRICE_RULE_CONFIGURATION = 5
  INVALID_PRICE_RULE_EXECUTOR_CONFIG = 6
end